<template>
  <div class="conversations-page">
    <div class="page-head">
      <div>
        <h1 class="page-title">Conversations</h1>
        <p class="page-subtitle">What kids talk about, with summarised sessions · first names only</p>
      </div>
      <el-radio-group v-model="range" size="small" @change="load">
        <el-radio-button label="7d">7 days</el-radio-button>
        <el-radio-button label="30d">30 days</el-radio-button>
      </el-radio-group>
    </div>

    <div v-loading="loading">
      <!-- KPI row -->
      <div class="kpi-row">
        <div class="card kpi">
          <div class="kpi-value">{{ kpis.talkHours }}<span class="kpi-unit">h</span></div>
          <div class="kpi-label">AI talk time</div>
        </div>
        <div class="card kpi">
          <div class="kpi-value">{{ kpis.talkSessions }}
            <span v-if="deltas.talkSessions !== null && deltas.talkSessions !== undefined" class="kpi-delta" :class="deltas.talkSessions >= 0 ? 'good' : 'bad'">
              {{ deltas.talkSessions >= 0 ? '▲' : '▼' }}{{ Math.abs(deltas.talkSessions) }}%
            </span>
          </div>
          <div class="kpi-label">talk sessions</div>
        </div>
        <div class="card kpi">
          <div class="kpi-value">{{ kpis.avgTurnsPerSession }}</div>
          <div class="kpi-label">avg turns / session</div>
        </div>
        <div class="card kpi">
          <div class="kpi-value">{{ kpis.topicsDetected }}</div>
          <div class="kpi-label">topics detected</div>
        </div>
        <div class="card kpi">
          <div class="kpi-value">{{ kpis.screenedMessages ? formatNumber(kpis.screenedMessages) : '—' }}</div>
          <div class="kpi-label">messages screened</div>
        </div>
        <div class="card kpi">
          <div class="kpi-value muted-val">{{ kpis.moderationFlags === null || kpis.moderationFlags === undefined ? 'not tracked' : kpis.moderationFlags }}</div>
          <div class="kpi-label">moderation flags</div>
        </div>
      </div>

      <div class="two-col">
        <!-- Topic chips -->
        <div class="card">
          <h4 class="card-subtitle">Fleet topics</h4>
          <div v-if="topics.length" class="topic-cloud">
            <el-tag v-for="t in topics" :key="t.topic" size="medium" class="topic-tag">
              {{ t.topic }} <b>{{ t.mentions }}</b>
            </el-tag>
          </div>
          <div v-else class="card-empty">No topics detected in this period.</div>
        </div>
        <div class="card">
          <h4 class="card-subtitle">About this view</h4>
          <p class="note">Summaries are generated by the voice agent at session end. Click a session to read the full transcript. Kid names are first-name-only by policy; parent contacts are never shown.</p>
        </div>
      </div>

      <!-- Session feed + transcript -->
      <div class="feed-grid">
        <div class="card feed">
          <h4 class="card-subtitle">Sessions</h4>
          <div v-if="summaries.length" class="session-list">
            <div v-for="s in summaries" :key="s.id"
              class="session-row" :class="{ selected: selectedId === s.id }"
              @click="openTranscript(s)">
              <div class="session-main">
                <span class="session-headline">{{ s.headline || s.summary }}</span>
                <span class="session-meta mono">{{ s.macAddress }} · {{ s.turns }} turns · {{ shortDate(s.updatedAt) }}</span>
              </div>
              <div class="session-tags" v-if="s.tags && s.tags.length">
                <span v-for="tag in s.tags.slice(0, 3)" :key="tag" class="mini-tag">{{ tag }}</span>
              </div>
            </div>
          </div>
          <div v-else class="card-empty">No conversations summarised in this period.</div>
        </div>

        <div class="card transcript" v-loading="transcriptLoading">
          <h4 class="card-subtitle">Transcript</h4>
          <template v-if="transcript">
            <p class="transcript-headline">{{ transcript.headline }}</p>
            <div class="transcript-lines">
              <div v-for="(line, i) in transcript.lines" :key="i" class="line" :class="line.role === 'assistant' ? 'agent' : 'kid'">
                <span class="line-speaker">{{ line.speaker }}</span>
                <span class="line-text">{{ line.text }}</span>
              </div>
            </div>
          </template>
          <div v-else class="card-empty">Select a session to read its transcript.</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Api from '@/apis/api';

export default {
  name: 'Conversations',
  data() {
    return {
      range: '7d',
      loading: false,
      kpis: {},
      deltas: {},
      topics: [],
      summaries: [],
      transcript: null,
      transcriptLoading: false,
      selectedId: null
    };
  },
  created() {
    this.load();
  },
  methods: {
    formatNumber(v) {
      return Number(v).toLocaleString('en-IN');
    },
    shortDate(value) {
      if (!value) return '—';
      return new Date(value).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
    },
    load() {
      this.loading = true;
      this.transcript = null;
      this.selectedId = null;
      Api.admin.getFounderConversations(this.range, ({ data }) => {
        this.loading = false;
        if (data.code === 0 && data.data) {
          this.kpis = data.data.kpis || {};
          this.deltas = data.data.deltas || {};
          this.topics = (data.data.sections && data.data.sections.topics) || [];
          this.summaries = (data.data.sections && data.data.sections.summaries) || [];
        } else {
          this.$message.error(data.msg || 'Failed to load conversations');
        }
      });
    },
    openTranscript(session) {
      this.selectedId = session.id;
      this.transcriptLoading = true;
      Api.admin.getConversationTranscript(session.sessionId, ({ data }) => {
        this.transcriptLoading = false;
        if (data.code === 0 && data.data) {
          this.transcript = data.data;
        } else {
          this.$message.error(data.msg || 'Failed to load transcript');
        }
      });
    }
  }
}
</script>

<style lang="scss" scoped>
@import '@/styles/theme.scss';

.conversations-page {
  max-width: 1280px;
}

.page-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}

.page-title {
  margin: 0;
  font-family: $font-display;
  font-size: 34px;
  font-weight: 400;
  line-height: 1.05;
  letter-spacing: -0.025em;
  color: $text-dark;

}

.page-subtitle {
  margin: 7px 0 0;
  font-size: 13px;
  color: $text-gray;
  max-width: 62ch;

}

.kpi-row {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  gap: 12px;
  margin-bottom: 14px;
}

.card {
  background: $surface;
  border: 1px solid $border-color;
  border-radius: $radius-lg;
  padding: 22px 24px;
  box-shadow: none;
  min-width: 0;

}

.kpi-value {
  font-family: $font-display;
  font-size: 40px;
  font-weight: 400;
  line-height: 1;
  letter-spacing: -0.03em;
  color: $text-dark;


  &.muted-val {
    font-size: 14px;
    color: $text-gray;
    line-height: 34px;
  }
}

.kpi-unit {
  font-size: 16px;
  color: $text-gray;
  letter-spacing: 0;
  margin-left: 4px;

}

.kpi-delta {
  font-size: 11px;
  font-weight: 600;

  &.good { color: $success; }
  &.bad { color: $danger; }
}

.kpi-label {
  font-family: $font-mono;
  font-size: 9.5px;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.11em;
  color: $text-light;
  margin-top: 10px;

}

.two-col {
  display: grid;
  grid-template-columns: 3fr 2fr;
  gap: 12px;
  margin-bottom: 14px;
}

.card-subtitle {
  margin: 0 0 16px;
  font-size: 13.5px;
  font-weight: 590;
  color: $text-dark;

}

.topic-cloud {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.topic-tag {
  background: rgba($primary, 0.1);
  border-color: transparent;
  color: $primary-dark;

  b { margin-left: 4px; }
}

.note {
  margin: 0;
  font-size: 12px;
  color: $text-gray;
  line-height: 1.6;
}

.feed-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.session-list {
  max-height: 420px;
  overflow-y: auto;
}

.session-row {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 9px 8px;
  border-radius: 8px;
  cursor: pointer;
  border-bottom: 1px solid #f4f5fa;

  &:hover { background: rgba($primary, 0.06); }
  &.selected { background: rgba($primary, 0.12); }
}

.session-main {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.session-headline {
  font-size: 12.5px;
  color: $text-dark;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.session-meta {
  font-size: 10.5px;
  color: $text-gray;
}

.session-tags {
  display: flex;
  gap: 4px;
  flex-shrink: 0;
}

.mini-tag {
  font-size: 10px;
  background: $divider-color;
  color: $text-gray;
  border-radius: 6px;
  padding: 1px 6px;
}

.transcript {
  min-height: 300px;
}

.transcript-headline {
  margin: 0 0 8px;
  font-size: 13px;
  font-weight: 600;
  color: $text-dark;
}

.transcript-lines {
  max-height: 380px;
  overflow-y: auto;
}

.line {
  display: flex;
  gap: 8px;
  padding: 5px 8px;
  border-radius: 8px;
  margin-bottom: 4px;
  font-size: 12.5px;

  &.agent { background: rgba($primary, 0.08); }
  &.kid { background: #f4f5fa; }
}

.line-speaker {
  font-weight: 700;
  flex-shrink: 0;
  width: 72px;
  word-break: break-word;
  color: $text-gray;
  font-size: 11px;
  padding-top: 1px;
}

.line-text {
  color: $text-dark;
  white-space: pre-wrap;
  word-break: break-word;
}

.card-empty {
  padding: 32px 0;
  text-align: center;
  color: $text-light;
  font-size: 12.5px;

}

.mono {
  font-family: $font-mono;
  font-size: 11.5px;
  letter-spacing: -0.01em;

}

@media (max-width: 1100px) {
  .kpi-row { grid-template-columns: repeat(3, 1fr); }
  .two-col, .feed-grid { grid-template-columns: 1fr; }
}
</style>
