module.exports = {
  apps: [
    {
      name: "manager-api",
      script: "npm",
      args: "start",
      cwd: "/root/cheeko-backend/main/manager-api-node",
      interpreter: "none",
    },
    {
      name: "manager-web",
      script: "npm",
      args: "run serve",
      cwd: "/root/cheeko-backend/main/manager-web",
      interpreter: "none",
    },
    {
      name: "mqtt-gateway",
      script: "app.js",
      cwd: "/root/cheeko-backend/main/mqtt-gateway",
      interpreter: "node",
      watch: false,
      env: {
        EMQX_HOST: "127.0.0.1",
      },
    },
    {
      name: "livekit-media-api",
      script: "media_api.py",
      cwd: "/root/cheeko-backend/main/livekit-server",
      interpreter: "python3",
      watch: false,
    },
    {
      name: "cheeko-agent",
      script: "env/bin/python",
      args: "workers/cheeko_worker.py dev",
      cwd: "/root/cheeko-backend/main/livekit-server",
      interpreter: "none",
      env: {
        PORT: "8081",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
    },
    {
      name: "math-tutor-agent",
      script: "env/bin/python",
      args: "workers/math_tutor_worker.py dev",
      cwd: "/root/cheeko-backend/main/livekit-server",
      interpreter: "none",
      env: {
        PORT: "8082",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
    },
{
      name: "riddle-solver-agent",
      script: "env/bin/python",
      args: "workers/riddle_solver_worker.py dev",
      cwd: "/root/cheeko-backend/main/livekit-server",
      interpreter: "none",
      env: {
        PORT: "8085",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
    },
    {
      name: "word-ladder-agent",
      script: "env/bin/python",
      args: "workers/word_ladder_worker.py dev",
      cwd: "/root/cheeko-backend/main/livekit-server",
      interpreter: "none",
      env: {
        PORT: "8086",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "2G",
    },
    {
      name: "content-poc",
      script: "env/bin/streamlit",
      args: "run app.py --server.port 8501 --server.headless true",
      cwd: "/root/cheeko-backend/content-poc",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
  ],
};
