ALTER TABLE ai_agent
ADD COLUMN IF NOT EXISTS soul TEXT,
ADD COLUMN IF NOT EXISTS runtime_agent_name VARCHAR(100);

ALTER TABLE ai_agent_template
ADD COLUMN IF NOT EXISTS soul TEXT,
ADD COLUMN IF NOT EXISTS runtime_agent_name VARCHAR(100);
